"""Initial schema: 20 tables + resolved_policies view

Revision ID: 9675ebfa3638
Revises: 
Create Date: 2026-05-13 09:19:24.230577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9675ebfa3638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_health_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('lie_rate', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('lie_rate', sa.Float(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('bypass_attempt_count', sa.Integer(), nullable=False),
    sa.Column('judge_decision_count', sa.Integer(), nullable=False),
    sa.Column('suprawall_connected', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bypass_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detection_logic', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_name')
    )
    op.create_table('compliance_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_type', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('control_name', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('incident_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('scenario_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id')
    )
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('incident_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('gemini_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('score_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('local_rule_id', sa.String(length=50), nullable=True),
    sa.Column('gemini_cache_hit', sa.Boolean(), nullable=False),
    sa.Column('playbook_id', sa.String(length=50), nullable=True),
    sa.Column('response_status', sa.String(length=20), nullable=False),
    sa.Column('forensics_status', sa.String(length=20), nullable=False),
    sa.Column('judge_decision_id', sa.String(length=36), nullable=True),
    sa.Column('bypass_detected', sa.Boolean(), nullable=False),
    sa.Column('deterministic_classification', sa.Boolean(), nullable=False),
    sa.Column('resolved_policy_id', sa.String(length=36), nullable=True),
    sa.Column('odp_override_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('industry_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('odp_set', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('template_id')
    )
    op.create_table('judge_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_rules', sa.JSON(), nullable=False),
    sa.Column('bypass_patterns_detected', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('resolved_policy_id', sa.String(length=36), nullable=True),
    sa.Column('odp_overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('nist_baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('baseline_id', sa.String(length=50), nullable=False),
    sa.Column('incident_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_threshold', sa.String(length=20), nullable=False),
    sa.Column('auto_contain_enabled', sa.Boolean(), nullable=False),
    sa.Column('escalation_contacts', sa.JSON(), nullable=False),
    sa.Column('response_time_sla_seconds', sa.Integer(), nullable=False),
    sa.Column('forensic_level', sa.String(length=20), nullable=False),
    sa.Column('notify_targets', sa.JSON(), nullable=False),
    sa.Column('compliance_report', sa.Boolean(), nullable=False),
    sa.Column('record_threshold', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id'),
    sa.UniqueConstraint('incident_type')
    )
    op.create_table('odp_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conflict_id', sa.String(length=50), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=False),
    sa.Column('odp_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_id')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('playbook_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('incident_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_type'),
    sa.UniqueConstraint('playbook_id')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=False),
    sa.Column('odp_id', sa.String(length=36), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suprawall_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('external_event_id', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('matched_rules', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('bypass_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('payload_sample', sa.Text(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['bypass_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('package_data', sa.JSON(), nullable=False),
    sa.Column('export_path', sa.String(length=500), nullable=True),
    sa.Column('integrity_hash', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_table('incident_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('intent_category', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('contains_injection_patterns', sa.Boolean(), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('contains_credentials', sa.Boolean(), nullable=False),
    sa.Column('contains_exfiltration', sa.Boolean(), nullable=False),
    sa.Column('contains_system_commands', sa.Boolean(), nullable=False),
    sa.Column('full_metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_odps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=False),
    sa.Column('odp_key', sa.String(length=100), nullable=False),
    sa.Column('odp_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['nist_baselines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('playbook_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('playbook_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('playbook_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('steps_failed', sa.Integer(), nullable=False),
    sa.Column('steps_pending_review', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('source_component', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=50), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('policy_file', sa.String(length=500), nullable=True),
    sa.Column('cli_command', sa.Text(), nullable=True),
    sa.Column('cli_stdout', sa.Text(), nullable=True),
    sa.Column('cli_stderr', sa.Text(), nullable=True),
    sa.Column('cli_returncode', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['response_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Create resolved_policies VIEW
    op.execute("""
    CREATE VIEW IF NOT EXISTS resolved_policies AS
    SELECT
        nb.id AS baseline_id,
        nb.incident_type,
        nb.severity AS baseline_severity,
        nb.auto_contain_enabled AS baseline_auto_contain,
        nb.escalation_contacts AS baseline_escalation_contacts,
        nb.response_time_sla_seconds AS baseline_sla,
        nb.forensic_level AS baseline_forensic_level,
        nb.notify_targets AS baseline_notify_targets,
        nb.compliance_report AS baseline_compliance_report,
        nb.record_threshold AS baseline_record_threshold,
        ood.odp_key,
        ood.odp_value,
        ood.value_type
    FROM nist_baselines nb
    LEFT JOIN organization_odps ood ON nb.id = ood.baseline_id AND ood.is_active = 1
    WHERE nb.is_active = 1
    """)

    op.create_table('human_review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('step_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('override_action', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['step_record_id'], ['response_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_review_tasks')
    op.drop_table('response_steps')
    op.drop_table('timeline_events')
    op.drop_table('response_records')
    op.drop_table('playbook_actions')
    op.drop_table('organization_odps')
    op.drop_table('incident_metadata')
    op.drop_table('evidence_packages')
    op.drop_table('bypass_attempts')
    op.drop_table('suprawall_events')
    op.drop_table('policy_versions')
    op.drop_table('playbooks')
    op.drop_table('odp_conflicts')
    op.drop_table('nist_baselines')
    op.drop_table('judge_decisions')
    op.drop_table('industry_templates')
    op.drop_table('incidents')
    op.drop_table('gemini_cache')
    op.drop_table('detection_rules')
    op.drop_table('demo_scenarios')
    op.drop_table('compliance_mappings')
    op.drop_table('bypass_patterns')
    op.drop_table('audit_log')
    op.drop_table('agents')
    op.drop_table('agent_health_history')
    op.execute("DROP VIEW IF EXISTS resolved_policies")
    # ### end Alembic commands ###
