"""add incident_type to incidents

Revision ID: b2de966705b7
Revises: 9675ebfa3638
Create Date: 2026-05-13 09:41:34.274068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2de966705b7'
down_revision = '9675ebfa3638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('incident_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'incident_type')
    # ### end Alembic commands ###
