"""Seed data for DetectionRule table.

One rule per incident type with regex patterns for deterministic matching.
"""

from app.core.constants import INCIDENT_TYPES, IncidentSeverity

DETECTION_RULES_SEED = [
    {
        "rule_id": "RULE-DEL-001",
        "name": "Data Destruction Pattern",
        "rule_type": "signature",
        "severity": IncidentSeverity.CRITICAL,
        "incident_type": "AGT-DEL-001",
        "pattern": "DROP TABLE|DELETE FROM\\s+\\w+\\s+WHERE\\s+1\\s*=\\s*1|TRUNCATE TABLE|rm\\s+-rf|shred\\s+-|del\\s+/[fqs]",
        "threshold": 0.6,
        "is_active": True,
    },
    {
        "rule_id": "RULE-FIN-002",
        "name": "Unauthorized Financial Action",
        "rule_type": "signature",
        "severity": IncidentSeverity.CRITICAL,
        "incident_type": "AGT-FIN-002",
        "pattern": "transfer\\s*\\$?\\d+[\\d,]*\\.?\\d*|wire\\s*transfer|swift\\s*payment|bank\\s*account\\s*\\d+|credit\\s*card\\s*\\d{4}[\\s-]?\\d{4}|bitcoin\\s*address|wallet\\s*0x[a-fA-F0-9]{40}",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-PER-003",
        "name": "Permission Escalation",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-PER-003",
        "pattern": "sudo\\s+|chmod\\s+777|chown\\s+root|setuid|privilege\\s*escalation|escalate\\s*privileges|grant\\s+all\\s+privileges|ROLE\\s+ADMIN",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-HRM-004",
        "name": "Harmful Output Generation",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-HRM-004",
        "pattern": "bomb\\s*making|weapon\\s*instructions|poison\\s*recipe|self.?harm|suicide\\s*method|hate\\s*speech|child\\s*exploitation",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-EXT-005",
        "name": "Data Exfiltration",
        "rule_type": "signature",
        "severity": IncidentSeverity.CRITICAL,
        "incident_type": "AGT-EXT-005",
        "pattern": "scp\\s+.*@|rsync\\s+.*:\\s*/|curl\\s+.*https?://.*\\s+-d|wget\\s+.*\\s+-O\\s+\\-|base64\\s+.*\\|\\s*curl|dns\\s*exfiltration|pastebin|gist\\.github\\.com",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-INJ-006",
        "name": "Prompt Injection",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-INJ-006",
        "pattern": "ignore\\s+previous\\s+instructions|disregard\\s+all\\s+prior|DAN\\s*mode|jailbreak|system\\s*override|you\\s+are\\s+now\\s+\\w+|new\\s*persona|developer\\s*mode",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-HAL-007",
        "name": "Hallucination Cascade",
        "rule_type": "signature",
        "severity": IncidentSeverity.MEDIUM,
        "incident_type": "AGT-HAL-007",
        "pattern": "I\\s+apologize,?\\s+but\\s+I\\s+cannot|I\\s+don\\'t\\s+have\\s+access\\s+to|conflicting\\s+information|cascade\\s*failure|recursive\\s*error|inconsistent\\s*output",
        "threshold": 0.6,
        "is_active": True,
    },
    {
        "rule_id": "RULE-CRE-008",
        "name": "Credential Exposure",
        "rule_type": "signature",
        "severity": IncidentSeverity.CRITICAL,
        "incident_type": "AGT-CRE-008",
        "pattern": "password\\s*[:=]\\s*\\S+|api[_-]?key\\s*[:=]\\s*\\S+|secret\\s*[:=]\\s*\\S+|token\\s*[:=]\\s*\\S+|-----BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY-----|AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9_]{36}",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-RAT-009",
        "name": "Rate Limit Abuse",
        "rule_type": "signature",
        "severity": IncidentSeverity.MEDIUM,
        "incident_type": "AGT-RAT-009",
        "pattern": "rate\\s*limit\\s*exceeded|429\\s+Too\\s+Many\\s+Requests|throttle|burst\\s*limit|quota\\s*exceeded",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-DRF-010",
        "name": "Model Drift",
        "rule_type": "signature",
        "severity": IncidentSeverity.MEDIUM,
        "incident_type": "AGT-DRF-010",
        "pattern": "model\\s*drift|distribution\\s*shift|KL\\s*divergence\\s*>|accuracy\\s*degradation|prediction\\s*variance",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-TLM-011",
        "name": "Tool Misuse",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-TLM-011",
        "pattern": "tool\\s*misuse|unauthorized\\s*tool|function\\s+not\\s+allowed|schema\\s*violation|parameter\\s*injection",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-GAP-012",
        "name": "Coverage Gap",
        "rule_type": "signature",
        "severity": IncidentSeverity.LOW,
        "incident_type": "AGT-GAP-012",
        "pattern": "uncategorized\\s*event|unknown\\s*action|no\\s*policy\\s*match|unhandled\\s*exception",
        "threshold": 0.7,
        "is_active": True,
    },
    {
        "rule_id": "RULE-SPY-013",
        "name": "Systematic Espionage",
        "rule_type": "signature",
        "severity": IncidentSeverity.CRITICAL,
        "incident_type": "AGT-SPY-013",
        "pattern": "reconnaissance|port\\s*scan|nmap\\s+-|masscan|enumerate\\s*users|directory\\s*listing|\\.git\\s+exposed|\\.env\\s+exposed",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-BYP-014",
        "name": "Guardrail Bypass",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-BYP-014",
        "pattern": "bypass\\s*guardrail|context\\s*window\\s*displacement|indirect\\s*tool\\s*chaining|homoglyph|confidence\\s*hijacking|unicode\\s*spoof|token\\s*smuggling",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-PRV-015",
        "name": "Privacy Violation",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-PRV-015",
        "pattern": "PII\\s*detected|SSN\\s*\\d{3}-\\d{2}-\\d{4}|email\\s*:\\s*\\S+@\\S+|phone\\s*:\\s*\\d{3}-\\d{3}-\\d{4}|GDPR\\s*violation|HIPAA\\s*breach|unauthorized\\s*data\\s*access",
        "threshold": 0.5,
        "is_active": True,
    },
    {
        "rule_id": "RULE-REG-016",
        "name": "Regulatory Trigger",
        "rule_type": "signature",
        "severity": IncidentSeverity.HIGH,
        "incident_type": "AGT-REG-016",
        "pattern": "regulatory\\s*violation|compliance\\s*breach|audit\\s*failure|SOX\\s*violation|PCI\\s*DSS\\s*failure",
        "threshold": 0.5,
        "is_active": True,
    },
]
