"""Seed data for IndustryTemplate table."""

INDUSTRY_TEMPLATES_SEED = [
    {
        "template_id": "TPL-HIPAA",
        "name": "HIPAA Healthcare",
        "description": "Healthcare compliance template with ODP presets for HIPAA-covered entities. Elevates severity for incidents involving PHI, mandates DPO notification, and enables full forensic capture.",
        "odp_set": {
            "AGT-DEL-001": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["ciso@company.com", "legal@company.com", "dpo@company.com"]',
                "response_time_sla": "300",
                "forensic_level": "FULL",
                "notify_targets": '["compliance", "legal", "engineering"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
            "AGT-EXT-005": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["ciso@company.com", "dpo@company.com"]',
                "response_time_sla": "300",
                "forensic_level": "FULL",
                "notify_targets": '["compliance", "legal"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
            "AGT-PRV-015": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["dpo@company.com", "legal@company.com"]',
                "response_time_sla": "600",
                "forensic_level": "FULL",
                "notify_targets": '["compliance", "legal"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
        },
    },
    {
        "template_id": "TPL-SOC2",
        "name": "SOC2 SaaS",
        "description": "SOC 2 Type II compliance template for SaaS providers. Focuses on access controls, monitoring, and audit trail completeness.",
        "odp_set": {
            "AGT-DEL-001": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["security@company.com", "ops@company.com"]',
                "response_time_sla": "900",
                "forensic_level": "FULL",
                "notify_targets": '["security", "engineering"]',
                "compliance_report": "true",
                "record_threshold": "10",
            },
            "AGT-EXT-005": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["security@company.com"]',
                "response_time_sla": "900",
                "forensic_level": "FULL",
                "notify_targets": '["security", "engineering"]',
                "compliance_report": "true",
                "record_threshold": "5",
            },
        },
    },
    {
        "template_id": "TPL-FINTECH",
        "name": "FinTech PCI-DSS",
        "description": "Financial services template prioritizing incidents involving cardholder data, transaction integrity, and fraud detection.",
        "odp_set": {
            "AGT-DEL-001": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["ciso@company.com", "risk@company.com", "cto@company.com"]',
                "response_time_sla": "180",
                "forensic_level": "FULL",
                "notify_targets": '["risk", "compliance", "engineering"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
            "AGT-FIN-002": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["risk@company.com", "cfo@company.com"]',
                "response_time_sla": "60",
                "forensic_level": "FULL",
                "notify_targets": '["risk", "compliance", "executive"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
        },
    },
    {
        "template_id": "TPL-GDPR",
        "name": "GDPR General",
        "description": "General Data Protection Regulation template for EU organizations. Emphasizes data subject rights, breach notification, and cross-border transfer controls.",
        "odp_set": {
            "AGT-EXT-005": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["dpo@company.com", "legal@company.com"]',
                "response_time_sla": "3600",
                "forensic_level": "FULL",
                "notify_targets": '["dpo", "legal"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
            "AGT-PRV-015": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["dpo@company.com"]',
                "response_time_sla": "1800",
                "forensic_level": "FULL",
                "notify_targets": '["dpo", "legal"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
        },
    },
    {
        "template_id": "TPL-STARTUP",
        "name": "SaaS Startup",
        "description": "Lightweight template for early-stage startups. Balances security with operational pragmatism. Defaults to logging and notification rather than aggressive containment.",
        "odp_set": {
            "AGT-DEL-001": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "false",
                "escalation_contacts": '["founders@company.com", "eng-lead@company.com"]',
                "response_time_sla": "3600",
                "forensic_level": "STANDARD",
                "notify_targets": '["engineering"]',
                "compliance_report": "false",
                "record_threshold": "100",
            },
            "AGT-EXT-005": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["founders@company.com"]',
                "response_time_sla": "1800",
                "forensic_level": "STANDARD",
                "notify_targets": '["engineering", "founders"]',
                "compliance_report": "false",
                "record_threshold": "50",
            },
        },
    },
    {
        "template_id": "TPL-FINANCE",
        "name": "Financial Services",
        "description": "Template for non-PCI financial services. Focuses on market manipulation, unauthorized trading, and regulatory reporting.",
        "odp_set": {
            "AGT-FIN-002": {
                "severity_threshold": "CRITICAL",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["risk@company.com", "compliance@company.com", "ceo@company.com"]',
                "response_time_sla": "120",
                "forensic_level": "FULL",
                "notify_targets": '["risk", "compliance", "executive"]',
                "compliance_report": "true",
                "record_threshold": "1",
            },
            "AGT-DEL-001": {
                "severity_threshold": "HIGH",
                "auto_contain_enabled": "true",
                "escalation_contacts": '["ops@company.com", "risk@company.com"]',
                "response_time_sla": "600",
                "forensic_level": "FULL",
                "notify_targets": '["ops", "engineering"]',
                "compliance_report": "true",
                "record_threshold": "5",
            },
        },
    },
]
